### ISSUE TITLE
Wrong attribute parsing

### ISSUE THREAD

**Issue by YerkoPalma** [shama/bel#62]
I'm having problems with bel. I try to use bel to render some markdown content with the help of marked library. With this code

```js
const html = require('yo-yo')
const marked = require('marked')

const post = require('./posts/post.md')
console.log(marked(post))
document.body.appendChild(html(marked(post)))
```

And this markdown content

```md
# hello world
```
I'm using [stringify](https://github.com/JohnPostlethwait/stringify) to require the `.md` file content. When I console log the `marked(post)` call, I get

```text
<h1 id="hello-world">hello world</h1>
```

That's pretty valid html to me, but bel complains with this error.

>Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'hello-world"' is not a valid attribute name.
>    at belCreateElement (http://playground-yerkopalma.c9users.io:8080/bundle.js:1447:14)
>    at http://playground-yerkopalma.c9users.io:8080/bundle.js:1807:12
>    at http://playground-yerkopalma.c9users.io:8080/bundle.js:1569:45
>    at Object.1../posts/post.md (http://playground-yerkopalma.c9users.io:8080/bundle.js:7:27)
>    at s (http://playground-yerkopalma.c9users.io:8080/bundle.js:1:254)
>    at e (http://playground-yerkopalma.c9users.io:8080/bundle.js:1:425)
>    at http://playground-yerkopalma.c9users.io:8080/bundle.js:1:443

And the problem is that when the belCreateElement function is called, it is called with wrong attributes

![error](https://cloud.githubusercontent.com/assets/5105812/21930603/ac2b754e-d975-11e6-91dd-0a156a1ce7d2.png)

Now why is that happening? I thought about an hyperx error, but tried it with hyperscript and it render correctly. Not sure what could it be, also looked at the [hyperscript-attribute-to-property](https://github.com/feross/hyperscript-attribute-to-property) library inside hyperx, but again why would it work with hyperscript, but not with bel?

Any help would be appreciated.

**Comment by roobie** [comment]
I've experienced the same issue. Funny thing is:

This does not work, as @YerkoPalma states above:
```javascript
html(htmlAsText)
```

However, this works:
```javascript
eval('html`' + htmlAsText + '`');
```

Which leads me to the suspicion that there is some conditional somewhere in the library that makes the parsing go differently depending on whether it is used as a template string or as an ordinary function.

(Tested in Chromium Version 55.0.2883.75 built on Debian stretch/sid, running on Debian 9.0 (64-bit))

**Comment by yoshuawuyts** [comment]
I don't completely follow why you're trying to call it through `bel` this
way; it'd break when using yo-yoify. If you're looking for an example of
how to use bel + marked I did some work for the choo handbook here
https://github.com/yoshuawuyts/choo-handbook/blob/master/index.js. Hope
this helps (:

**Comment by roobie** [comment]
Personally, I used `'choo/html'` but the `Error` is thrown in `bel`, which is why I chimed in here, but I may be a bit off =)

**Comment by yoshuawuyts** [comment]
No that's cool, but what I'm saying is that calling bel() as a function
instead of a tagged template literal is something you should probably never
do - instead there are probably better ways to achieve what you're trying
to achieve. (e.g. DOMNode.setInnerHTML and the like)

**Comment by blahah** [comment]
@yoshuawuyts I use `html(foo)` quite a lot in choo. It's useful whenever you want to use some externally supplied HTML. Can you elaborate on why it's a bad idea? Apart from this issue of course, which seems like a bug.

**Comment by yoshuawuyts** [comment]
Oh cool, didn't know folks did that - guess it wasn't an intentional
consequence but ueh yeah that's actually pretty neat.

**Comment by roobie** [comment]
@blahah you've never had the `DOMException` thrown from `bel` when doing that?

**Comment by blahah** [comment]
@roobie I have, only with certain elements. It always happens with `<img src="..." />`, but quite often I don't get the error.

I was suggesting that the usage pattern of passing HTML to `html()` is useful, and questioning why it would be a bad idea. I'd love to see this solved.

**Comment by YerkoPalma** [comment]
I guess that the problem might be related with yo-yoify. As it is a browserify transform, it can make a difference if it is called like 

```js
bel(str)
``` 
or like 

```js
bel`${str}`
```

Because of the parsing made by [yo-yoify](https://github.com/shama/yo-yoify). Also, it is only my thoughts as I havent check the code yet.
