### ISSUE TITLE
bel 5 breaks on-load for server rendering

### ISSUE THREAD

**Issue by toddself** [shama/bel#80]
```
↳ node --version
6.10.3
↳ npm i bel
test@1.0.0 /home/todd/src/test
└── bel@5.0.0 
↳ node
> var bel = require('bel')
undefined
> var onload = require('on-load')
undefined
> var el = bel`<div>hello, world</div>`
undefined
> onload(el, () => console.log('loaded'))
TypeError: el.setAttribute is not a function
    at onload (/home/todd/src/t/node_modules/on-load/index.js:33:6)
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
> .exit
↳ npm rm bel && npm i bel@^4
- is-electron@2.0.0 node_modules/is-electron
- bel@5.0.0 node_modules/bel
test@1.0.0 /home/todd/src/test
└── bel@4.6.0 
↳ node
> var bel = require('bel')
undefined
> var onload = require('on-load')
undefined
> var el = bel`<div>hello, world</div>`
undefined
> onload(el, () => console.log('loaded'))
DOMElement {
  tagName: 'DIV',
  nodeName: 'DIV',
  className: '',
  dataset: {},
  childNodes: 
   [ DOMText {
       data: 'hello, world',
       length: 12,
       ownerDocument: [Object],
       parentNode: [Circular] } ],
  parentNode: null,
  style: {},
  ownerDocument: 
   Document {
     head: 
      DOMElement {
        tagName: 'HEAD',
        nodeName: 'HEAD',
        className: '',
        dataset: {},
        childNodes: [],
        parentNode: [Object],
        style: {},
        ownerDocument: [Circular],
        namespaceURI: 'http://www.w3.org/1999/xhtml',
        _attributes: {} },
     body: 
      DOMElement {
        tagName: 'BODY',
        nodeName: 'BODY',
        className: '',
        dataset: {},
        childNodes: [],
        parentNode: [Object],
        style: {},
        ownerDocument: [Circular],
        namespaceURI: 'http://www.w3.org/1999/xhtml',
        _attributes: {} },
     documentElement: 
      DOMElement {
        tagName: 'HTML',
        nodeName: 'HTML',
        className: '',
        dataset: {},
        childNodes: [Object],
        parentNode: null,
        style: {},
        ownerDocument: [Circular],
        namespaceURI: 'http://www.w3.org/1999/xhtml',
        _attributes: {} },
     childNodes: [ [Object] ],
     nodeType: 9 },
  namespaceURI: 'http://www.w3.org/1999/xhtml',
  _attributes: { null: { 'data-onloadidle6i': [Object] } } }
```

**Comment by toddself** [comment]
This seems to be an issue with pelo

**Comment by toddself** [comment]
However, the more I think about it, perhaps on-load should be a no-op in the browser?
